apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=300
            - -c
            - log_min_messages=LOG
          env:
            - name: POSTGRES_DB
              value: alfresco
            - name: POSTGRES_PASSWORD
              value: alfresco
            - name: POSTGRES_USER
              value: alfresco
          image: postgres:13.1
          name: postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "536870912"
      restartPolicy: Always
status: {}
