apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: solr6
  name: solr6
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr6
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: solr6
    spec:
      containers:
        - env:
            - name: ALFRESCO_SECURE_COMMS
              value: none
            - name: SOLR_ALFRESCO_HOST
              value: alfresco
            - name: SOLR_ALFRESCO_PORT
              value: "8080"
            - name: SOLR_CREATE_ALFRESCO_DEFAULTS
              value: alfresco,archive
            - name: SOLR_SOLR_HOST
              value: solr6
            - name: SOLR_SOLR_PORT
              value: "8983"
          image: alfresco/alfresco-search-services:2.0.1
          name: solr6
          ports:
            - containerPort: 8983
          resources:
            limits:
              memory: "2147483648"
      restartPolicy: Always
status: {}
